# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('cover', models.URLField(max_length=300, unique=True)),
                ('psPrice', models.URLField(default=None)),
                ('xboxPrice', models.IntegerField(default=None, null=True)),
                ('psExchange', models.BooleanField(default=False)),
                ('xboxExchange', models.BooleanField(default=False)),
                ('psOnly', models.BooleanField(default=False)),
                ('xboxOnly', models.BooleanField(default=False)),
                ('availableOnXbox', models.BooleanField(default=True)),
                ('availableOnPs', models.BooleanField(default=True)),
                ('psOnlyPrice', models.BooleanField(default=False)),
                ('xboxOnlyPrice', models.BooleanField(default=False)),
            ],
        ),
    ]
