# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20160811_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
