# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0005_game_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('exchange', models.IntegerField(default=False)),
                ('new', models.IntegerField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='availableOnPs',
        ),
        migrations.RemoveField(
            model_name='game',
            name='availableOnXbox',
        ),
        migrations.RemoveField(
            model_name='game',
            name='psExchange',
        ),
        migrations.RemoveField(
            model_name='game',
            name='psNew',
        ),
        migrations.RemoveField(
            model_name='game',
            name='psOnlyPrice',
        ),
        migrations.RemoveField(
            model_name='game',
            name='psPrice',
        ),
        migrations.RemoveField(
            model_name='game',
            name='psUsed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xboxExchange',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xboxNew',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xboxOnlyPrice',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xboxPrice',
        ),
        migrations.RemoveField(
            model_name='game',
            name='xboxUsed',
        ),
        migrations.AddField(
            model_name='dvd',
            name='game',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='owner',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
