# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170608_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='availableOnPs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='availableOnXbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='psExchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='psNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='psOnlyPrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='psPrice',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='psUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='xboxExchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='xboxNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='xboxOnlyPrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='xboxPrice',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='xboxUsed',
            field=models.BooleanField(default=False),
        ),
    ]
