# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20170608_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='console',
            field=models.CharField(choices=[('xbox', 'xbox one'), ('ps', 'ps4')], default='xbox one', max_length=30),
        ),
    ]
