# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_dvd_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='comment',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
