# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_dvd_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='id_igdb',
            field=models.BigIntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.CharField(default=None, max_length=300, unique=True),
        ),
    ]
