# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_dvd_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='psOnly',
            new_name='psExclusive',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='xboxOnly',
            new_name='xboxExclusive',
        ),
        migrations.AlterField(
            model_name='dvd',
            name='state',
            field=models.CharField(choices=[(b'available', b'available'), (b'sold', b'sold'), (b'exchanged', b'exchanged'), (b'deleted', b'deleted')], default=b'available', max_length=30),
        ),
    ]
