# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='facebook_location',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_location_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
