# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170615_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
