# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170615_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_short_name',
        ),
    ]
