# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_facebook_has_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
