# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAuths',
            new_name='UserAuth',
        ),
    ]
