FB_PROFILE_PIC_PART1 = "https://graph.facebook.com/"
FB_PROFILE_PIC_PART2 = "/picture?type=large"
LARGE_PROFILE_PIC_URL = "/img/details_profile.png"

FB_ACCESS_TOKEN = "EAAMFSTFTluYBAJ1tKIMX26iP5XO0JoTPtxJn5e2L6KQWHSpmtl3rie4xMgXrHj88KS5SSKdSqk6YjFetgnFMFOQnO16hIAxFzSS6iHHTau6NoWp9tMNYnBc3W8OoeAfUb0MZA2y43dUoM0l6y1F6SNIxPxJsZD"
